// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Health.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Grpc.Health.V1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Version : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"major")]
        public int Major { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"minor")]
        public int Minor { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"patch")]
        public int Patch { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HealthCheckRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"service")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Service { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CheckInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"check_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CheckName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"is_successful")]
        public bool IsSuccessful { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"diagnostic_info")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DiagnosticInfo { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HealthCheckResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"status")]
        public ServingStatus Status { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"diagnostic")]
        public global::System.Collections.Generic.List<CheckInfo> Diagnostics { get; set; } = new global::System.Collections.Generic.List<CheckInfo>();

        [global::ProtoBuf.ProtoMember(3, Name = @"service_version")]
        public Version ServiceVersion { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum ServingStatus
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
            Unknown = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"SERVING")]
            Serving = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"NOT_SERVING")]
            NotServing = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PingRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PingResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"service_version")]
        public Version ServiceVersion { get; set; }

    }

    [global::System.ServiceModel.ServiceContract(Name = @"Health")]
    public interface IHealth
    {
        global::System.Threading.Tasks.Task<HealthCheckResponse> Check(HealthCheckRequest value, global::ProtoBuf.Grpc.CallContext context = default);
        global::System.Threading.Tasks.Task<PingResponse> Ping(PingRequest value, global::ProtoBuf.Grpc.CallContext context = default);
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
